// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebProject;

namespace TestWebProject.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20200912203822_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TestWebProject.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User 3"
                        });
                });

            modelBuilder.Entity("TestWebProject.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Action 1",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Action = "Action 2",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Action = "Action 3",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("TestWebProject.UserLog", b =>
                {
                    b.HasOne("TestWebProject.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
